dist: bionic
language: node_js
node_js:
  - 12

addons:
  apt:
    packages:
      - libgconf-2-4
  sonarcloud:
    organization: vetrosound
    token:
      secure: XfGVZgOii6RdccaJMFlV9U2WEF+ncYJPLela/aP5QiN0wQF0UPQQHeUP76iW5b2hJyBrLLsl2hrZCk2y34B6lolGUc0/CROk/o+7pnx1UY5UeG9Ko+s8cq9Mfw1ARRQuBE9/ZHpGgt6rvV1xj2pUETprkzFn0mVRIJ4eaeSf081jYdW09+otRr+LP3OCq1ePoMBEkz7rbDMe33iZQiYBomqbON7U9VwENXEfooIRJKATtkvoIAx459zRhYWtl4bEtzv/t7QnO1keJTYEXY9gO+MZOtZQ8OV43JVnf6sJX7oid7ztNIMXEue/M8baLQiVsAMHt28s+FRYNNbcAJRx7TLhbg3c90Y2obzouzSHuVAPMLvVEvCnEHGmwJpB5lnRkdLAkolqfTxaN5FXYi66CJFo8br9aKUAE9Q0Xk1aesCvddphGZdRmQSJlYfwsc8YSWuxh7pr5zNytReEeDpyxlOum4hbcYUKXGNKw24qCww4yLDRTW5tx848Y/5s1yevFA7n99mGnz2ieP3RAjTcFRfdFTCNOVPJvWMik08Qy+iuBRfMjwA3P0I0sbGOCy5MxOwpSpkLqqRwSe6npjI9BmcJi+TyFPA/TvpSss3fagiZwzjlJuSakG0ieMJDjq99AJe9Y7gEUkXFZIaXSnHT5NESn9JEaEuA5vddBkX7uBg=

cache:
  yarn: true
  directories:
    - ~/.cache
    - ~/.sonar/cache

branches:
  only:
    - master

install:
  - yarn

script:
  - yarn lint
  - yarn test
  - yarn build:prod
  - yarn cy:verify
  - yarn cy:run
  - sonar-scanner

notifications:
  email: false
  slack:
    on_success: always
    on_failure: change
    rooms:
      - secure: J1g8j4MdBZoAb5JZ3AfiaDpj3FCZMItrmYshJHRQ8kYowEVHZYeRFrIaRegRFCLUJLKsJ6a35VyB6GzYwAdKx97UKS5bT5TMAfvNj+6arZkZMxKUahdtO4dYZRufXtl36FcbYkNZ+t4gu6e9P0DhymXHwS00YPZjF++C4RiZxeqYbkrfzd/BOJa93vKmwNNk4vaDaevFtDE/KIEp/LHJSgTKLTIGlclw9etlvhjFzPLyCNgJoyZKtvC4l8k8WMUamvqq+qkelElhNw4Jd8bNk9y7INZmiYjNO1w118sKl5FxjG2oJjbDU4NA5QwXn1aXvfHN5MqmwVzrdkCmAV5z0MO3Yo979uyx5A/BPBymbWUsl97TadpKL3MVHYISIde+TQnyHEADjxWEnkP0AYHVmBdVzXOe+3YDGub3wnuOzjtpUN7coX7jGSfUUnLUncLP3CwGBW/2L9MF9iNPSUZMEpW1WGZTc7gHBnFqkzmqgb8drTUa8NAk+GwBVx2sgd4RRc93Db90Crh6+rSPmgfCrm70OzCqL2v0sn5BdAkyLeF+fP5WnjHKJvqRG269kOnPvcGGMJmEgMGvBbNwGPuWfB83+B6GCt8ixGiZzfiiHte6fsaHcPzgF9QxiX7RpFaN5EkB1IXhTGXKXIoQMMyOukB8bmNW6QLQNjCesbLnlsg=
